### ISSUE TITLE
Open Data Standard for FS Reg Workstream - Standard Project Contribution and Onboarding

### ISSUE THREAD

**Issue by Taniem100** [finos/community#179]
## Business Problem
There has been a 700% increase in regulation since 2008 financial crisis, and we’re seeing 79% of compliance spending devoted to personnel costs [McKinsey & Co 2018], with a staggering $55bn forecast to be spent on RegTech by 2025 [Bloomberg].  
Firms are under pressure to comply with an ever increasing volume and complexity of regulation whilst facing tighter margins. A large number of RegTech tools have been launched to address specific aspects of regulatory compliance, but the lack of common standards hinders interoperability, which diminishes their value and increases operational risk for firms. This is an industry-wide issue which would benefit from a collaborative approach to the development and adoption of a standard way of classifying regulatory obligations and linking them to a firm’s business profile.
As an added benefit, this would enhance the value of the overall RegTech ecosystem and reduce barriers to entry in financial services.

 
## Proposed Solution
Creating an open data standard comprising a taxonomy (common vocabulary for describing regulatory obligations and firms’ business profiles), an ontology (a schema which describes the relationships between firms’ business profiles and their regulatory obligations) and a simple reference implementation (to demonstrate how to use the taxonomy and ontology). The objective is to provide users with a reliable way to answer these three questions:  
- WHICH regulations apply to me?
- WHAT obligations arise from these regulations
- HOW do I comply with these obligations?
Key benefit: By leveraging a knowledge graph of financial services regulation, we can benefit from massive horizontal scalability, enabling us to start small and gain exponentially increasing utility of the data standard as new domains are added.

## Tentative Roadmap
An initial delivery of the open data standard for Financial Services regulation will be released via the cloud in Q3 2022. 
Discussion on further requirements will continue in parallel, expanding the model as deemed necessary by the participants and proposing additional codes and/or features for the model, during Q3 and Q4 2022. Full details in the [project roadmap].

## Scope (optional)
The open data standard will include the material definitions required for Liquidity Reporting covering key jurisdictions within USA, UK, EU, APAC.

## Current State
A model has already been drafted and, work is underway to make this available to invited members for the initial incubation stage of the project
 
## Existing Materials
N/A

## Development Team
- Taniem Choudhury, Deutsche Bank
- Sarah Sinclair, Change Gap
- James Nicholls, Braithwate

### Maintainers
TBD

### Confirmed contributors
- Deutsche Bank
- Morgan Stanley
- Goldman Sachs
- Wells Fargo
- BNY Mellon
- REGnosys
- APIAX
- FinReg-E
- MyComplianceCentre

### Target Contributors
Contributors should have experience of Taxonomy development and/or Liquidity Reporting

## Infrastructure needs
Describe the FINOS infrastructure you will need for this project, in addition to a GitHub repository. The FINOS team will connect with you before setting up any of this infrastructure:
- Recurring meetings: Bi-weekly WG meetings
- Mailing list: opendatafsreg@finos.org
- A project on the Legend Studio shared instance - https://legend.finos.org/studio

# What's next?
Open Data Standard for FS Reg Workstream – Project Plan Proposal

## Stage 1 - Planning – near complete
- Agree on concept with participants and define an outline Taxonomy and Ontology
- Agree use case to identify participants who want to get involved. [Liquidity Reporting]
- Feasibility analysis – to get a view of commitment needed from participants
- FINOS contributions – relevant component review [Morphir, Legend]
- Milestone – WG to agree on plan for initiative
- Timeline – December 2021 to end of Feb 2022 (3 sessions)

## Stage 2 – Design (Part 1: Open Data Standard)
- Design of relevant taxonomy branches (prudential regulation, firms, obligations etc.)
- Design of ontology schema
- Initial focus on Liquidity Reporting use case to formulate design
- Milestone – to agree on the model & sign off from the OpenDataStandard working group
- Timeline – March 2022 to end of June 2022 (6 sessions)

## Stage 3 – Design (Part 2: regulatory data model)
- Design of regulatory data model (selected liquidity regs in UK, EU, USA, APAC)
- Define model governance 
- Milestone – to agree on the workflow design and submit it for build
- Timeline – by end of Sep 2022

## Stage 4 - Build
- Review the model with PRA, Fed/OCC, EBA before publishing it into PROD
- Build and Testing 
- Milestone – to have an accepted data standard and user workflow for maintenance, for initial use case of Liquidity Reporting
- Timeline – by end of Nov 2022

-----

# Contribution process (v. 1.0, last updated on May 26, 2021)
Below is the list of tasks that FINOS Team and the contribution author go through in order to complete the FINOS contribution process.
**Please do not edit these contents at contribution time!**

## FINOS Contrib POC
- [x] Identify and Assign FINOS Contrib POC : @robmoffat / @mcleo-d 

## Kick-off meeting
- [x] Set up kick-off meeting with project leads to cover
    - [x] [FINOS overview](https://www.finos.org/hubfs/An%20Introduction%20to%20FINOS.pdf) (if necessary)
    - [x] [FINOS Maintainers cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet/) 
    - [x] Discuss project proposal

## Proposal (Lead Maintainer)
- [x] Lead maintainer to send out announcement to community@finos.org using this template:
    
    ```
    Dear FINOS Community, 
    
    We would like to propose a new FINOS project. Please review the proposal details at (_TODO: add link to the GitHub issue proposal_).
    
    If you're interested in participating, please :+1: the GitHub issue proposal and drop a comment with your name, org and email

   Thanks a lot,
   ```

## Identify project meta (Lead: FINOS Contrib POC, Support: FINOS Marketing)
- [x] Project Name. - Sarah & Taniem still in discussions about this.  `oasis`
    - [x] Standard Name   
    - [x] Assess current trademark status
    - [x] Define new project name (if applicable)
    - [ ] Design new project logo (if applicable)
    - [ ] Trademark new project name and logo (if applicable)
- [ ] Define project slug 
- [ ] (optional) Which FINOS SIG is sponsoring this contribution
- [x] Category and sub-category (for FINOS Landscape).  Enablement / Regulation
- [ ] Create new GitLab repository
- [x] Team composition: identify lead maintainer and other maintainers
    - Lead: @
    - Other Maintainers: @Taniem100, @oliversalmon
- [x] Need meetings? `Yes`
- [x] Need meeting minutes, agenda, attendance tracking? `Yes`

## Maintainers, contributors and CLAs (Lead: FINOS Contrib POC, Support: FINOS infra)
- [x] For each maintainer identified in the previous step, collect: the following info:  `sent email 20/9/22 to confirm'
  - Fullname
  - GitLab username
  - Corporate email address

- [x] Maintainers to determine if participants will be required to execute a Community Specification License Agreement (CSLA) or submit a Pull Request to accept the license terms. - CLA Bot will handle
- [x] (optional) Check if maintainers, editors, and other participants are covered by a FINOS CSLA - CLA Bot will handle
- [ ] Talk to Sally Ellard & Mark Hoare at the DB OSPO about contributing to the project. - Taniem / Oliver

## Project Communication Channel(s)
- [x] Ask maintainers which communications channels they'd like to use
- Asynchronous
  - [ ] GitLab Issues (_public_)
  - [x] Groups.io - `Proposed name: opendatareg@lists.finos.org`. - leave for now
- Synchronous
  - [ ] FINOS Slack Channel (general _public Slack_ / leadership _private Slack_) YES
  - [x] Regular Friday AM Meeting
- [ ] Create the identified communication channels during infra set up
- [ ] Link communication channels linked front and center in the project README.md

## Approval (Lead: FINOS Infra)
- [x] Assign issue to Executive Director (@mindthegab) to trigger voting
 (optional). If additional socialization is required, the Executive Director may bring standards projects to the FINOS Governing Board
- [x] FINOS accepts the contribution/new standard project (and the contribution process can move forward)

## Infra setup (Lead: FINOS Infra)
- [ ] Create mailing-list into Groups.io
- [ ] Create GitLab sub-project under https://gitlab.com/finosfoundation/legend/ , using https://github.com/finos/standards-project-blueprint as template
- [ ] Invite contributors to [GitLab finosfoundation/legend group](https://gitlab.com/finosfoundation/legend/)
- [ ] Set maintainers into GitLab finosfoundation/legend group new sub-project
- [ ] Aggregate new mailing list into community@finos.org
- [ ] Enable meeting attendance tracking (into GitLab)
- [ ] Onboard into legend.finos.org/studio

## Metadata update (Lead: FINOS Infra)
- [ ] Add project to metadata
- [ ] Add identities, orgs and affiliations to metadata
- [ ] Add logo to FINOS landscape
- [ ] Add maintainers emails to finos-project-maintainers@finos.org list
- [ ] Onboard project on LF systems ([SFDC](https://jira.linuxfoundation.org/browse/SOPS), Insights, EasyCLA, Groups.io)

## Announcement (Lead: FINOS Contrib POC)
- [ ] Work with FINOS marketing to send out announcement to announce@finos.org , checkout announcement template at the [Contribution page](https://community.finos.org/docs/governance/Software-Projects/contribution).
- [ ] Notify FINOS Contrib POC and FINOS marketing manager once the announcement has been sent out (FINOS infra)

## Marketing collateral and Social (Lead: FINOS Marketing)
- [ ] Update FINOS marketing collaterals to update numbers and include the new project
- [ ] Post on FINOS social media
- [ ] Post on LF social media
- [ ] Email brief announcement to lf_staff@linuxfoundation.org (Optional depending applicability of contribution)

## Onboarding and training (Lead: FINOS Infra)
- [ ] FINOS Standards Project Governance
- [ ] FINOS Standards Project Lifecycle

## Press Release (OPTIONAL - Lead: FINOS Marketing)
- [ ] Identify quotes for press release
- [ ] Draft press release
- [ ] Send embargoed press release to reporters

**Comment by maoo** [comment]
Dear @Taniem100 , thanks for creating the issue! I've took the freedom to update the checklist; we'll discuss the next steps internally and get back to you. Thank you!

**Comment by robmoffat** [comment]
Hi @Taniem100,

Are you aware of this?  https://github.com/finos/community/issues/177

Probably, but I thought I'd just check

**Comment by stephengoldbaum** [comment]
+1

**Comment by noelmcloughlin** [comment]
Great proposal.
 
I'm curious if the Open Data Standard is truly open.  Q. will any parts of W3C Semantic Architecture be support for Ontology, Taxonomy, vocabulary development and information exchange?  See diagram which guides me.  Its [compatible with Akoma Ntoso](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.1060.5300&rep=rep1&type=pdf).

Using open standards means FinReg deliverables can be integrated with existing Ontologies, allowing KG, reasoning, fact discovery, etc, and benefits of semantic technologies.  

Note - [LinkML](https://linkml.io/) is good abstraction layer since RDF/XML is designed for machines, not humans. 

![semantic-web-architectures-3](https://user-images.githubusercontent.com/13322818/161823542-5f0aff92-de36-4603-ab5d-6fcfa50ebbe3.png)

**Comment by noelmcloughlin** [comment]
+1

**Comment by mtronci** [comment]
+1 from the FS Industry Solutions team in Google Cloud, we are interested to contribute to this submission.
We propose to also work on a SQL based implementation of the use case, which we think can represent an accessible and multi-platform manner to express the overall requirements.

**Comment by dehrich123** [comment]
+1

**Comment by jnicholls82** [comment]
> Great proposal.
> 
> I'm curious if the Open Data Standard is truly open. Q. will any parts of W3C Semantic Architecture be support for Ontology, Taxonomy, vocabulary development and information exchange? See diagram which guides me. Its [compatible with Akoma Ntoso](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.1060.5300&rep=rep1&type=pdf).
> 
> Using open standards means FinReg deliverables can be integrated with existing Ontologies, allowing KG, reasoning, fact discovery, etc, and benefits of semantic technologies.
> 
> Note - [LinkML](https://linkml.io/) is good abstraction layer since RDF/XML is designed for machines, not humans.
> 
> ![semantic-web-architectures-3](https://user-images.githubusercontent.com/13322818/161823542-5f0aff92-de36-4603-ab5d-6fcfa50ebbe3.png)

Hi Noel,

Yes, the intention is to make this as open as possible, and leverage/extend existing standards where possible - Akoma Ntoso is a good example of a standard we seek to use (in this case, as the standard for the meta data associated with each regulatory document). 

Other open elements of the stack include:
- JSON as the data exchange languge for communicating the open taxonomies 
- RDFS based knowledge graph (probably based on Apache Jena)
- SPARQL queries to answer the key questions of: "Which regulations apply to my firm?" / "What obligations arise from these regulations?" / "How do I comply with these obligations?"

Would love to engage with you further on this!

Kind regards,
James

**Comment by mindthegab** [comment]
Given the extensive socialization, alignment with OpenRegtech and Support from the Community, I am happy to formally approve this project for incubation in FINOS. Congrats @Taniem100, @jnicholls82 and Sarah and I look forward to seeing this succeed.

@mcleo-d @maoo @jgavronsky @TheJuanAndOnly99 @robmoffat FYI, please proceed.

**Comment by jnicholls82** [comment]
Thanks @mindthegab - excited to be formally part of the FINOS community!

**Comment by mcleo-d** [comment]
Thanks for the approval @mindthegab and congratulations @Taniem100, @jnicholls82 and Sarah! 🚀 

I've added the approval to this week's Regulation Innovation meeting to inform the SIG about the exciting news ... 

https://github.com/finos/open-regtech-sig/issues/42

**Comment by robmoffat** [comment]
@sarahsinclair @Taniem100  can you & your team  provide an update on whether there is further work to do on this onboarding?  

I feel like we might have finished the initial pass. 

thanks,
Rob

**Comment by robmoffat** [comment]
Closing this contribution until a future time when open source infrastructure / repos are required.

**Comment by oliver-buckley-salmon-db** [comment]
Hi @robmoffat please can we have a repo now, to store the turtle files in, as we build out the ontology schema and example data? We are ready to get started with defining them.
Thanks

**Comment by mindthegab** [comment]
I would recommend this project consider starting in finos-labs https://github.com/finos-labs, which is exactly the place to experiment ahead of contribution - FYI @mcleo-d

**Comment by robmoffat** [comment]
@oliver-buckley-salmon-db, 

What would you like the repo to be called?  I will set up access for all the GitHub handles we collected for you guys already.

thanks,
Rob

**Comment by robmoffat** [comment]
Hi @oliver-buckley-salmon-db,

I've created a private repo and invited you, and the rest of the folks with GitHub Ids identified by Sarah and me.  React out to help@finos.org If you have any issues, or want further users added to the repo.

**Comment by oliver-buckley-salmon-db** [comment]
Thanks very much @robmoffat
