### ISSUE TITLE
JupyterLab Templates - Software Project Contribution and Onboarding

### ISSUE THREAD

**Issue by timkpaine** [finos/community#215]
# JupyterLab Templates - Software Project Contribution and Onboarding
 
I'd like to propose a new track for FINOS around Jupyter Notebooks and their related tools. As Jupyter has become the de-facto standard tool for data science around the world, it has also found its way into the hands of buy and sell side business analysts, traders, and quantitative researchers. Coding has become an [essential tool for finance](https://archive.ph/OfkvK) and has begun to unseat excel as the data analysis tool of choice for the [industry](https://www.forbes.com/sites/googlecloud/2020/03/11/beyond-spreadsheets/?sh=1fc7b33676c7).
 
 
Additionally, as more and more financial organizations begin to explore open source, Jupyter ecosystem tooling has become a popular avenue for participation. Here is a brief survey of the open source presence of some buy and sell side institutions, and one can see the presence of numerous Jupyter ecosystem projects:
 
- JP Morgan: [https://github.com/jpmorganchase](https:/[github.com/jpmorganchase](http://github.com/jpmorganchase))
- Two Sigma: [https://github.com/twosigma/beakerx](https:/[github.com/twosigma/beakerx](http://github.com/twosigma/beakerx))
- Bloomberg: [https://github.com/jupyter-widgets/ipywidgets](https:/[github.com/jupyter-widgets/ipywidgets](http://github.com/jupyter-widgets/ipywidgets)), [https://github.com/bqplot/bqplot](https:/[github.com/bqplot/bqplot](http://github.com/bqplot/bqplot)),  [https://github.com/bloomberg/ipydatagrid](https:/[github.com/bloomberg/ipydatagrid](http://github.com/bloomberg/ipydatagrid))
- Man AHL: [https://github.com/man-group/dtale](https:/[github.com/man-group/dtale](http://github.com/man-group/dtale)), [https://github.com/man-group/notebooker](https:/[github.com/man-group/notebooker](http://github.com/man-group/notebooker))
- DE Shaw: [https://www.deshaw.com/research/desco-quansight-improving-jupyter-efficiency](https:/[www.deshaw.com/research/desco-quansight-improving-jupyter-efficiency](http://www.deshaw.com/research/desco-quansight-improving-jupyter-efficiency))
 
Additionally, it is my understanding that JP Morgan, Two Sigma, and Bloomberg have employed Jupyter core maintainers as employees, and numerous other financial organizations have contributed directly to Jupyter projects.
 
Currently, I maintain 4 Jupyter-based projects under the JP Morgan GitHub organization, as well as Perspective under the FINOS organization (which also features a Jupyter widget as a core aspect of its functionality). These projects are currently being actively used by many financial institutions and FINOS member organizations, and I believe the establishment of a new track for Jupyter ecosystem projects will help foster wider collaboration. I have several projects ready for incubation under this new track should it be adopted.
 
As an inaugural project, I’d like to propose the [JupyterLab Templates](https://github.com/jpmorganchase/jupyterlab_templates) project. This is a relatively established and widely used project that would benefit from incubation in FINOS, and allow for further collaboration across the open source member ecosystem.
 
## Business Problem
Jupyter notebooks are the de facto standard tool for data scientists, quantitative researchers, and business analysts. Often times, they want to work from standard project templates. As an example, a risk quant might want a set of standard notebooks that they can quickly create, fill in a few details, and run. An analysts might want a “company profile” notebook they can quickly instantiate, fill in a company name, and generate a report. The first building block of these is the ability to package and distribute template notebooks, which is the functionality provided by the JupyterLab Templates library.
 
## Solution
The JupyterLab Templates file lets you collect and install a collection of notebooks as part of your python (or other) package. It then integrates with the JupyterLab user interface to provide a new notebook card called “Template Notebook”. Clicking on this provides a browser which the user can use to select amongst any of the preinstalled notebook templates.
 
## Roadmap
There is a tentative roadmap in the project issues (https://github.com/jpmorganchase/jupyterlab_templates/issues). Immediate goals for the project are to reimplement the UI to be more intuitive and allow for better searching/filtering, to allow for bundled/tarball/git remote templates, integrate a notebook template with its runnable environment for reproducibility, and evangelize the notebook templates project to encourage greater participation amongst open source projects.
 
## Current State
Project is actively maintained by at least 2 employees of FINOS members. Project has 300 stars and ~9000 monthly downloads.
 
## Existing materials
https://github.com/jpmorganchase/jupyterlab_templates
 
## Development team
@timkpaine @vidartf (here and there)  @neilslinger (oversight)
 
## Contributor Commitment
@timkpaine will actively maintain this project for the foreseeable future, with collaboration from JP Morgan.
 
### Confirmed contributors
@timkpaine / @Point72 / [timothy.paine@cubistsystematic.com](mailto:timothy.paine@cubistsystematic.com)
 
### Target Contributors
Any and all, including those not affiliated with FINOS or involved in finance (I regularly receive feedback via email from academic and non-financial industry users).

## Project Communication Channel(s)
Just GitHub issues
 
## Infrastructure needs
None, just GitHub
 
## Understanding FINOS Onboarding Requirements
 
As a project onboarding into FINOS, you will need to familiarize yourself and your contributor team with the following materials:
 
- [x] [FINOS overview](https://www.finos.org/hubfs/An%20Introduction%20to%20FINOS.pdf) (if necessary)
- [x] [FINOS Maintainers cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet/)
- [x] [FINOS Project/Standards Governance](https://community.finos.org/docs/governance)
- [x] [FINOS Project Lifecycle](https://community.finos.org/docs/governance/Software-Projects/project-lifecycle)
- [x] Notify [help@finos.org](mailto:help@finos.org) that you have completed the _describing the contribution_ section.
 
# 2. FINOS Approval
 
Below is the list of tasks that the **FINOS Team** go through in order to complete the FINOS approval process.  At this point, a FINOS Point-of-Contact (POC) should be assigned to this GitHub issue.
 
**Please do not edit these contents when completing part 1, "describing the contribution" above.**
 
## Record The Contribution
- [x] Submit contribution to LF by opening a ticket via https://jira.linuxfoundation.org/browse/SS and marking contribution as "Exploratory"; attach a summary of the **Business Problem** and **Proposed Solution** (above) of the project. https://jira.linuxfoundation.org/browse/SS-1004
 
## Kick-off meeting
- [x] Set up kick-off meeting with project leads
- [x] Run kick-off meeting
  - [x] Walk through the checklist in part 1, ensure all the questions are answered and remove items that don't apply
  - [x] Write and send contribution proposal announcement (optional - see below)
 
## FINOS Contrib POC
- [x] Identify and Assign FINOS Project Coordinator - @TheJuanAndOnly99 
- [x] Identify and Assign FINOS Strategic Advisor - @jgavronsky 
 
## Proposal (Lead Maintainer)
- [x] Lead maintainer to send out announcement to [community@finos.org](mailto:community@finos.org) using this template:
   
    ```
    Dear FINOS Community,
    
    We would like to propose a new FINOS project. Please review the proposal details at (_TODO: add link to the GitHub issue proposal_).
   
    If you're interested in participating, please :+1: the GitHub issue proposal and drop a comment with your name, org and email
 
   Thanks a lot,
   ```
 
## Technical Steering Committee Approval
 
- [x] Prioritise this issue on the [TSC Backlog](https://github.com/orgs/finos/projects/39)
- [x] Assign this issue to @colineberhardt
- [x] Add the `ready-for-tsc` label
- [x] TSC to invite contributors to present their project
- [x] FINOS TSC approves/rejects the contribution
- [x] Ask @jgavronsky to mark contribution as "Engaged" within LF systems
- [x] (optional) If additional socialization is required, the Executive Director may bring projects to the FINOS Governing Board
- [x] Update the contribution status to "Engaged" by sending another email to **LF Legal Representative** with the name of the project and its new status.
 
## TSC Findings / Report
*TSC to enter findings summary here.*
 
# 3. Preparing For Onboarding
 
Before the FINOS team can onboard your project, there are a few housekeeping that need to be taken care of.  These must be completed by the contributor, with help if required from the POC or FINOS Infra.  
 
## Logo / Trademarks
- [x] Initiate transfer of trademarks to FINOS _(request help from [help@finos.org](mailto:help@finos.org) / LF Legal if needed)_
- [x] Request logo design from `[help@finos.org](mailto:help@finos.org)` _(if needed)_
- [x] The codebase doesn’t include any patent or copyright that conflicts with FINOS Governance and bylaws. _(POC to validate with FINOS Legal team if anything important is raised)_
 
## Coding Standards
- [x] The codebase doesn’t have HIGH or CRITICAL CVEs across direct and transitive libraries.  _Enable GitHub actions from [Security Scanning](https://github.com/finos/security-scanning) to ensure this._
- [x] The codebase doesn’t have any unfriendly licenses across direct and transitive libraries
- [x] (optional - if a build system is provided) The build process runs successfully
 
## FINOS Project Standards
- [x] [finos-admin](http://github.com/finos-admin) is Admin of the GitHub repository to transfer
- [x] Apply project blueprint contents - see [ODP docs](https://community.finos.org/docs/collaboration-infrastructure#finos-project-blueprint)
    - [x] README.md file contains the sections in the [README Template](https://github.com/finos/software-project-blueprint/blob/main/README.template.md)
    - [x] Project FINOS badge in README (incubating)
    - [x] [OpenSSF Passing Badge](https://bestpractices.coreinfrastructure.org/en)
    - [x] License in README
    - [x] Contributing in README
    - [x] `CONTRIBUTING.md` - missing Governance and other contents, see [FINOS blueprint version](https://github.com/finos/software-project-blueprint/blob/main/CONTRIBUTING.md)
    - [x] `LICENSE` (replace `{}` placeholders)
    - [x] Ensure that the proper project governance is in the CONTRIBUTING.md file
- [x] [All incubating criteria](https://community.finos.org/docs/governance/Software-Projects/stages/incubating) are checked and documented below
 
_Add documentation here_
 
# 4.  FINOS Onboarding
 
This is performed by FINOS Infra once the three previous stages are complete, with support from the contributor and the FINOS POC.
 
## Maintainers, Contributors and CLAs
- [x] Identify other existing contributors (assuming there's a contribution history (eg Git history)
- [x] Check if maintainers and other contributors are all covered by FINOS CLA
- [x] Engage with FINOS Legal team to figure out what’s needed to cover all maintainers and contributors with FINOS CLA
- [x] Reach out to contributors and employers to coordinate CLA signatures
 
## Validation (only if code is contributed)
- [x] The codebase doesn’t have HIGH or CRITICAL CVEs across direct and transitive libraries
- [x] The codebase doesn’t have any unfriendly licenses across direct and transitive libraries
- [x] (optional - if a build system is provided) The build process runs successfully
- [x] [finos-admin](http://github.com/finos-admin) is Admin of the GitHub repository to transfer
- [x] The codebase doesn’t include any patent or copyright that conflicts with FINOS Governance and bylaws (to be validated with FINOS Legal team)
- [x] Check project blueprint contents - see [ODP docs](https://community.finos.org/docs/collaboration-infrastructure#finos-project-blueprint)
- [x] [All incubating criteria](https://community.finos.org/docs/governance/Software-Projects/stages/incubating) are met (review documentation provided above)
 
## Code transfer
- [x] Backup (even with screenshot) GitHub permissions of the repository to transfer
- [x] Check GitHub repository transfer requirements:
  - [x] [finos-admin](http://github.com/finos-admin) has `Admin` to all repositories to transfer
  - [x] [finos-admin](http://github.com/finos-admin) ia allowed to transfer repositories out of the org
  - [x] if the repository is owned by a user (and not an org), the user must be able to transfer the repository to [finos-admin](http://github.com/finos-admin)
- [x] Transfer all code assets as GitHub repositories under [github.com/finos](http://github.com/finos)
- [x] Invite GitHub usernames to GitHub FINOS Org
- [x] Create `<project-name>-maintainers` GitHub team and invite users
- [x] Configure `finos-admins` (`Maintain` role) and `finos-staff` (`Triage` role) team permissions
 
## Project Communication Channel(s)
- [x] Create the identified communication channels during infra set up
- [x] Link communication channels linked front-and-center in the project README.md
 
## Infra setup
- [x] Enable EasyCLA
- [x] Add project to metadata
- [x] Add identities, orgs and affiliations to metadata (deprecated by EasyCLA)
- [x] Add logo to FINOS landscape
    - [x] Create `staging` branch on `finos/finos-landscape`
    - [x] Merge `finos/metadata` changes on master (will udpdate `landscape.yml` in `finos/finos-landscape`)
    - [x] Create PR from `staging` branch on `finos/finos-landscape`
    - [x] Review Netlify preview
    - [x] Merge PR
- [x] Add project maintainers emails to [[finos-project-maintainers@finos.org](mailto:finos-project-maintainers@finos.org)](https://groups.google.com/a/finos.org/g/finos-project-maintainers/members) list
- [x] Add project maintainers GitHub usernames to the [project-maintainers Team](https://github.com/orgs/finos/teams/project-maintainers/members)
- [x] Ask @jgavronsky to mark contribution as "Active" within LF systems
- Add `@finos` scope to https://github.com/finos/jupyterlab_templates/blob/main/js/package.json#L2 (see https://www.npmjs.com/package/jupyterlab_templates ) (project leads consider this disruptive for existing consumers, won't fix)
- [x] Create CVE and license scanning (see https://github.com/finos/community/issues/215#issuecomment-1794595817)
- [x] Enable automated dependency update, using [Renovate](https://renovatebot.com/)
- [x] Enable [branch protection](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches) (`Require a pull request before merging`)
 
# 5. Announcement
 
(Lead: FINOS Contrib POC)
 
- [x] Update the contribution status to "Active" by sending another email to **LF Legal Representative** with the name of the project and its new status.
- [x] Lead maintainer works with FINOS marketing to send out announcement to [announce@finos.org](mailto:announce@finos.org) , checkout announcement template at the [Contribution page](https://community.finos.org/docs/governance/Software-Projects/contribution#step-5-contribution-announcements)
- [x] Notify FINOS marketing (@grizzwolf + finos-marketing internal Slack channel)

DISCLAIMER: This e-mail message and any attachments are intended solely for the use of the individual or entity to which it is addressed and may contain information that is confidential or legally privileged. If you are not the intended recipient, you are hereby notified that any dissemination, distribution, copying or other use of this message or its attachments is strictly prohibited. If you have received this message in error, please notify the sender immediately and permanently delete this message and any attachments.

**Comment by maoo** [comment]
Thanks for this @timkpaine , it seems a very interesting contribution! We'll start working on this and reach out to organize a demo to our Technical Steering Committee. Apologies for the late response, we're very busy wrapping all up for https://www.finos.org/hosted-events/2022-12-08-open-source-in-finance-forum-new-york

**Comment by jonfreedman** [comment]
@ColinEberhardt not sure what you think but seems like a demo of this would be overkill. I think the relevant contribution principles are also satisfied based on interest from two member firms. @mindthegab @jgavronsky I don't know whether the proposal of a new "track" is part of the TSC remit or not?

**Comment by robmoffat** [comment]
@ColinEberhardt and I are going to discuss with @mindthegab  and @jgavronsky tomorrow... will get back to you @jonfreedman

**Comment by mindthegab** [comment]
@jonfreedman @ColinEberhardt @finos/technical-steering-committee 

I'd like to get a formal +1 from the TSC to at least accept the contribution of the https://github.com/jpmorganchase/jupyterlab_templates and then after contribution we can discuss the creation of a new SIG (Special Interest Group) which I believe would be the closest to the concept of "track" that @timkpaine has proposed.

We have some degree of urgency here (happy to chat 1:1) to complete this before the holidays, so also happy to work by slient consensus given there's already a general support for the project (2 firms involved, mature, etc).

Can we have a couple of +1s here?

**Comment by maoo** [comment]
Just checked (again) CVE and license scanning, all good (see below)

###  NodeJS
```
# Install production dependencies from the lockfile
cd js ; yarn install --frozen-lockfile --production

# License scanning; all identified licenses are compatible with (outbound) Apache 2.0 license
node-license-validator . --allow-licenses Apache-2.0 MIT BSD-2-Clause BSD-3-Clause ISC

# CVE scanning, no CVEs found
npx --yes auditjs ossi
```

### Python
```
# Generate requirements.txt and install scanning libs
poetry export --without-hashes -f requirements.txt --output requirements.txt
pip install safety pip-licenses

# CVE scanning,  0 vulnerabilities found, 0 vulnerabilities ignored
safety check --full-report -r requirements.txt

# License scanning; all identified licenses are compatible with (outbound) Apache 2.0 license
pip-licenses --allow-only="MIT License; BSD License; Apache Software License; Mozilla Public License 2.0 (MPL 2.0)"
```

I also noticed that [Makefile facilitates the use of semgrep](https://github.com/finos/jupyterlab_templates/blob/main/Makefile#L57), but it's not invoked by any Github Action, as far as I see ; it could be helpful to run Semgrep periodically and on code changes via Github Actions.

**Comment by maoo** [comment]
This is a recap of what's missing - @TheJuanAndOnly99 , could you please work on the following items and submit a Pull Request?

- CONTRIBUTING.md - missing Governance and other contents, see [FINOS blueprint version](https://github.com/finos/software-project-blueprint/blob/main/CONTRIBUTING.md)
- Link communication channels linked front-and-center in the project README.md
- [ ] Add `@finos` scope to https://github.com/finos/jupyterlab_templates/blob/main/js/package.json#L2 (see https://www.npmjs.com/package/jupyterlab_templates )
- [ ] Create CVE and license scanning (see https://github.com/finos/community/issues/215#issuecomment-1794595817)

**Comment by psmulovics** [comment]
[Reviewed ](https://lists.finos.org/g/toc/message/248) item as TOC member, I see no issues with progressing forward.

**Comment by TheJuanAndOnly99** [comment]
Hey @psmulovics thanks for the comment. We've actually stumbled into a bit of a "dispute" as the JupyterLab Templates maintainers believe that adding the @finos scope to the package name would be disruptive as it is already a popular/widely used package. We are going to bring this up to the FINOS TOC at the next meeting for resolution.

**Comment by psmulovics** [comment]
It has been allowed in some other cases as well to miss the scope and use tags, a good example is https://www.nuget.org/packages?q=Tags%3A%22finos%22 - only one package has the actual @finos scope in the name, the rest is using it as a tag.

**Comment by TheJuanAndOnly99** [comment]
All contribution activities have been completed. We can safely close this issue. Congratulations to the team!
