### ISSUE TITLE
April 19th Legend Office Hours Checklist  

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/community#250]
**April 19th Legend Office Hours Checklist**    

- [ ] Set up Zoom + 
- [ ] Schedule meetings (Eteri + Juan)
- [ ] Send out invites 
 - Inaugural meeting was created but will need to schedule the recurring meetings after the zoom account is created
- [ ] Gather + curate questions (Beeke + Jane)
- [ ] Beeke to check if GS can share recordings 
- [ ] Send out an announcement to the Legend mailing list 
- [ ] Sent announcement to TWAF
