### ISSUE TITLE
Infrastructure, Governance and Web properties cleanup after program disband

### ISSUE THREAD

**Issue by maoo** [finos/community#39]
Following all Programs agreeing to disband (see #31), and as the Board granted the FINOS team the necessary authority to amend policies and documents to complete the cleanup, the FINOS team needs to perform the following tasks:

- [x] #45 @copiesofcopies is working on a simplified Governance model which would replace the existing PGP and POP, as well provide consistency across current governance elements spread out at wiki.finos.org. We'll create an issue once there's an RFC ready for community socialization.

- [x] @aitana16 Archive / add deprecation notice for all Program information in the [FINOS wiki](http://finosfoundation.atlassian.net/wiki/spaces/FINOS/) 

- [x] @aitana16 Remove references to Program level mailing lists (but maintain lists as active) from [FINOS wiki](wiki.finos.org) and other FINOS web properties. Check with me for any questions. 

- [x] @toshaellison Removing the notion of programs from the website: Mainly finos.org/programs and this will likely done contextually to publishing a new FINOS project landscape. This should be completed by end of June. Tracking this here just for completeness. 

- [x] For this board meeting we will report only on focus project. For the next Board meeting We'll put forward a **Revised Project reporting process**: We are aiming for a largely automated project metrics reporting process, in opt-in mode for the project team, based on merged project and former program metrics (see  [ODP#107](https://github.com/finos/open-developer-platform/issues/107) @mindthegab)

- [x] @maoo Rename Program Status Dashboard in Project Status Dashboard in metrics.finos.org and also remove PMC centric visualizations - See https://github.com/finos/community/issues/39

- [x] @maoo Update github org description/link for all disbanded programs

- [x] @maoo updating ODP website to reflect new naming of governance structure

-  @mindthegab Get projects to adopt new project governance - tracking progress at https://github.com/finos/community/issues/58

- @copiesofcopies Once we identified a new governance, the **Community Handbook needs cleanup**: Review, cleanup and simplify the Community Handbook and / or propose new location - tracking progress at #48
Due to end of June.

**Comment by mindthegab** [comment]
@maoo I know you don't like multiple assignees but I think it's pertinent in this case.

**Comment by mindthegab** [comment]
@maoo just a reminder to take care of your tasks tomorrow here if possible. Thank you!

**Comment by maoo** [comment]
@mindthegab - re. github org update, I updated all orgs with the following sentence:

`<program name> Program within the Fintech Open Source Foundation (FINOS) - PLEASE NOTE! All repositories have been moved to https://github.com/finos`

I didn't update github.com/symphonyoss and github.com/HadoukenIO ; maybe we could update HadoukenIO ?

**Comment by mindthegab** [comment]
> I didn't update github.com/symphonyoss and github.com/HadoukenIO ; maybe we could update HadoukenIO ?
@maoo yeah, please do so.

**Comment by mindthegab** [comment]
This issue is done and open items are tracked in separate issues, therefore closing.
