### ISSUE TITLE
TimeBase Community Edition (WIP)

### ISSUE THREAD

**Issue by stuartfarr** [finos/community#70]
## Business Problem
Time-series data is foundational to both buy-side and sell-side financial services firms. The need for time-series data management systems is well understood and is well-served by products provided under commercial licenses. There are also many open-source time-series data systems but their uptake in financial services firms is less extensive, possibly due to insufficient performance and scalability or lack of appropriateness for financial services time-series data.
There is constant demand to reduce total cost of operating technology stacks, whilst at the same time implementing changes to serve new opportunities or meet new obligations. Implementing change in a cost-effective manner has led to an increase in the use of cloud and open-source technologies, and less of a “one size fits all” approach.

 
## Proposed Solution
Having been battle-tested in trading firms for over 10 years under a commercial license, TimeBase is now offered under an open-source license as TimeBase Community Edition”. TimeBase Community Edition was designed from inception for managing time-series data found in financial services. 

The goal is to provide enterprise grade time-series data management and messaging capability which enables financial services firms to use with other open-source and commercial components to augment existing solutions, create new solutions. 

TimeBase can be used, simultaneously, as a traditional time-series database and real-time data messaging/streaming server. Data structures (“streams”) are user-defined. There is a rich API for interacting (ingesting, streaming) with TimeBase, which provide the necessary hooks for data population and data utilization.

## Current State
*Summarize the history and current state of the project*
 
## Existing Materials
*If materials already exist, provide a link to them that Foundation staff can access - if it's in a private GitHub.com repositories, you should invite the finos-admin user with R/O permissions to those repositories*

## Development Team
*List out all of the current team members, including full name, affiliation, work email address, and GitHub.com username*

# Contribution process
Below is the list of tasks that FINOS Team and the contribution author go through in order to complete the FINOS contribution process.
**Please do not edit these contents at contribution time!**

## FINOS Contrib POC
- [x] Identify and Assign FINOS Contrib POC - _James McLeod_ - @mcleo-d 

## Identify project meta (Lead: FINOS Contrib POC, Support: FINOS Marketing)
- [x] Project Name
    - [x] Assess current trademark status - @stuartfarr - Does **Timebase CE** have an existing trademark?
    - [x] Define new project name (if applicable) - The project name has been confirmed as **Timebase CE**
    - [x] Design new project logo (if applicable) - The existing project logo is demonstrated on https://timebase.info/ and in the comments below ... https://github.com/finos/community/issues/70#issuecomment-721912996
    - [x] Trademark new project name and logo (if applicable) - @stuartfarr - Is **Timebase CE** trademarked as a project name?
- [x] Category and sub-category (for FINOS Landscape) - **Timebase CE** should be added to the **models** category of the FINOS Landscape - http://landscape.finos.org/ 
- [x] Existing code or new Github repository - **Timebase CE** has an existing GitHub repository as demonstrated in comment https://github.com/finos/community/issues/70#issuecomment-721905707 
- [x] Existing code releases (and which artefact repositories are used) - @avavilau to confirm with @maoo via @mcleo-d - see comment https://github.com/finos/community/issues/70#issuecomment-700634800
- [x] Team composition: lead maintainer and other maintainers - **Timebase CE** maintainers are @avavilau and @alex-karpovich as highlighted below
- [x] Meetings (existing/yes/no) - **no**
- [x] Meeting minutes, agenda, attendance tracking (existing/yes/no) - **no** // possible future scenario
- [x] Continuous Integration (existing/yes/no) - **yes** - To be discussed with @avavilau and @maoo
- [x] Documentation website (existing/yes/no) - **yes** - Currently exists as markdown and integrated into https://timebase.info/

## Maintainers, contributors and CLAs (Lead: FINOS Contrib POC, Support: FINOS infra)
- [x] For each maintainer identified in the previous step, collect: the following info: 
  - **TimeBase CE Lead Maintainer**
    - Full name : Aliaksei Vavilau  
    - GitHub username : @avavilau
    - Corporate email address : Aliaksei_Vavilau@epam.com
  - **TimeBase CE Maintainer**
    - Full name : Alex Karpovich  
    - GitHub username : @alex-karpovich
    - Corporate email address : Aliaksandr_Karpovich@epam.com
- [x] Identify other existing contributors (assuming there's a contribution history (eg Git history) - Project contributors all from EPAM Timebase team
- [x] Check if maintainers and other contributors are all covered by FINOS CLA
- [x] Engage with FINOS Legal team to figure out what’s needed to cover all maintainers and contributors with FINOS CLA
- [x] Reach out to contributors and employers to coordinate CLA signatures - _EPAM CCLA Status_ - https://github.com/finos/metadata/pull/732
- [x] Invite GitHub usernames to GitHub FINOS Org - https://github.com/finos/metadata/issues/761
- [x] Create `<project-name>-maintainers` GitHub team and invite users - https://github.com/finos/metadata/issues/762

## Code validation (only if code is contributed) (Lead: FINOS Infra)
- [x] The codebase doesn’t have HIGH or CRITICAL CVEs across direct and transitive libraries
- [x] The codebase doesn’t have any unfriendly licenses across direct and transitive libraries
- [x] (optional - if a build system is provided) The build process runs successfully
  - [x] [finos-admin](http://github.com/finos-admin) is Admin of the GitHub repository to transfer
- [x] The codebase doesn’t include any patent or copyright that conflicts with FINOS Governance and bylaws (to be validated with FINOS Legal team)
- [x] The codebase complies with FINOS Project Blueprint
- [x] [All incubating criteria](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530363/Incubating) are checked and documented below

## Voting (Lead: FINOS Infra)
- [x] Assign issue to @mindthegab to trigger voting
- [x] FINOS accepts the contribution (and the contribution process can move forward)

## Code transfer (Lead: FINOS Infra)
- [x] Rename https://github.com/epam/TimeBase to https://github.com/epam/TimeBase-CE
- [x] Check GitHub repository transfer requirements:
  - [x] [finos-admin](http://github.com/finos-admin) has `Admin` to all repositories to transfer
  - [x] [finos-admin](http://github.com/finos-admin) ia allowed to transfer repositories out of the org
  - [x] if the repository is owned by a user (and not an org), the user must be able to transfer the repository to [finos-admin](http://github.com/finos-admin)
- [x] Transfer all code assets as GitHub repositories under github.com/finos
- [x] Enable CLA Bot
- [x] Alex - Merge project blueprint files from https://github.com/finos/timebase-ce to https://github.com/epam/TimeBase
- [x] Alex - Update README.md to comply with template https://github.com/finos/software-project-blueprint/blob/main/README.template.md
  - [x] Update project badge - Added by @mcleo-d https://github.com/finos/TimeBase-CE/pull/175

## Announcement (Lead: FINOS Contrib POC)
- [x] Work with FINOS marketing to send out announcement to community@finos.org , checkout announcement template on https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/83034172/Contribute
- [ ] Coordinate social media promotion with FINOS marketing 
    - [ ] Post on FINOS social media
    - [ ] Post on LF social media
- [x] EPAM to deliver SVG logo with `TimeBase CE` underneath, based on this template - https://github.com/finos/finos-landscape/blob/master/hosted_logos/git-proxy.svg
  - Added by @mcleo-d here https://github.com/finos/branding/blob/master/project-logos/active-project-logos/Timebase/timebase-logo-upright.svg 

## Infra setup (Lead: FINOS Infra)
- [x] maoo - Delete https://github.com/finos/timebase-ce-tmp
- [x] Add project to metadata
- [x] Add identities, orgs and affiliations to metadata
- [x] Add logo to FINOS landscape - Added by @mcleo-d to https://github.com/finos/branding/tree/master/project-logos/active-project-logos/Timebase
- [x] Add project maintainers emails to finos-project-maintainers@finos.org list (Added Alex)
- [x] Add project maintainers GitHub usernames to the project-maintainers Team
- [x] Enable security vulnerabilities scanning (WhiteSource)
- Enable meeting attendance tracking

## First Release
- [x] Alex and mao - discuss about first public release
  - [x] Update release coordinates to include `finos`

## Onboarding and training
- [x] Enable EasyCLA, disable CLA Bot
- [x] FINOS Project Governance
- [x] FINOS Project Lifecycle
- [x] ODP Training

**Comment by avavilau** [comment]
Current State:
History:
2006 – Timebase 1.0 (historical data analytics, SQL)​
2010 – Timebase 2.0 (timeseries data base, live streaming)​
2015 – Timebase 5.0 (Very large databases, HDFS)​
2018 – IPC/UDP low latency mode (Timebase topics)​
2019 – Cloud support (REST/WS, Docker, Kuber)​
2020 – Timebase 6.0 Community Edition (open source) and Clustering 

TimeBase 6.0 is currently in progress, we are in the middle of moving project and CI/CD to GitHub from private repository.
Many TimeBase 6.0 features are also work in progress

**Comment by avavilau** [comment]
Existing Materials:
- [TimeBase repository](https://github.com/DeltixInc/TimeBase)
- [Web site](http://timebase.info/)
- [Documentation](https://kb.timebase.info/) (work in progress)

**Comment by avavilau** [comment]
Development Team:

https://github.com/stuartfarr - Business
https://github.com/avavilau - Delivery Manager
https://github.com/alex-karpovich - Solution Architect / Main Developer
https://github.com/alexei-osipov -  Solution Architect / Main Developer 
https://github.com/andymalakov - Solution Architect
https://github.com/Romkisel - Backend Developer
https://github.com/ypldan - Backend Developer
https://github.com/Maxim-Gadalov - Backend Developer
https://github.com/sizmestiev - C++ Developer
https://github.com/MitoZ - Front-end Developer
https://github.com/msamusenka - Solution Architect (Integrations)
https://github.com/ekarankow - Backend Developer (Integrations)
https://github.com/PolinaGurinovich - Front-end Developer (Integrations)
https://github.com/astrakh - QA Automation 
https://github.com/sr-remsha - Technical Writer

**Comment by avavilau** [comment]
Contribution process

Contribution guidelines are work in progress and not yet defined.

**Comment by ColinEberhardt** [comment]
Thanks for raising this contribution proposal, TimeBase looks like an interesting and useful product for the FINOS members and the wider community.

Considering that this is already a commercial product, I would be grateful if you could elaborate on the differences between the open source community edition and the paid-for enterprise version? This type of arrangement can cause conflict, you will certainly wish to retain sales of your commercial edition, and as a result, I expect that you will 'hold back' certain product features. However, for the community edition to be a success (beyond being a teaser for the commercial edition), it needs to be a well-rounded and useful product in its own right.

Can you please share your thoughts on this?

**Comment by stuartfarr** [comment]
@ColinEberhardt, thank you for question; your comment is well made. You can see the differences [here](https://timebase.info/why-timebase/product-editions.html). But some additional comments and context: TimeBase's original mission was (and is) to provide high performance time-series data management for systematic/algorithmic trading firms as part of larger product suite we provide. Many such firms are small and want "out of the box" capability. As such, we bundled data (ingest) connectors for many trading venues and associated market data structures (streams). These are not part of TimeBase Community Edition because we want and expect a much wider set of use-cases which may or may not need these connectors. Another piece of relevant background is that TimeBase was built by a small software company called Deltix, acquired by EPAM in February 2020. We (old Deltix) had considered making an open source contribution years before but the support of EPAM has given us the confidence to finally do it! TimeBase Community is emphatically not a teaser for the commercial product which, outside of the differences noted, is the same core engine as the enterprise edition. This is an important topic, please let me know if this comment addresses it.

**Comment by mcleo-d** [comment]
Please find the differences between Community Editon and Enterprise Edition below ...

![Screenshot 2020-10-26 at 18 00 51](https://user-images.githubusercontent.com/6029572/97210267-3de6fe00-17b5-11eb-9269-4407faf2395f.png)

**Comment by avavilau** [comment]
@mcleo-d  repository: https://github.com/DeltixInc/TimeBase

**Comment by avavilau** [comment]
- Aliaksei Vavilau and Alex Karpovich (maintainers)
- Rest of the team as members https://timebase.info/our-team.html

**Comment by avavilau** [comment]
TB Logo: https://timebase.info/assets/img/timebase-logo-new.svg

**Comment by mcleo-d** [comment]
Hey @stuartfarr - I'm currently updating the progression of the Timebase CE project contribution and was wondering if you have an update on inviting current Timebase users to join the project contribution?

It would be great if you could supply an update in the issue comments below.

Kind regards,

James.

**Comment by mcleo-d** [comment]
Hi @stuartfarr, @avavilau and @alex-karpovich,

Can you ask the following Timebase team members to accept their invitation to the FINOS organisation on GitHub as part of the Timebase CE project contribution 👍 
 
- [x] @stuartfarr
- [x] @andymalakov
- [x] @alex-karpovich
- [x] @alexei-osipov
- [x] @Romkisel
- [x] @alexey-ban
- [x] @bmcgreal
- [x] @MitoZ
- [x] @sizmestiev
- [x] @dpoguts
- [x] @ypldan
- [x] @astrakh
- [x] @Ga2nibal
- [x] @Sergei-Y
- [x] @msamusenka
- [x] @Maxim-Gadalov
- [x] @ekarankow
- [x] @PolinaGurinovich
- [x] @sateviss
- [x] @EkaterinaRunets
- [x] @sr-remsha

Many thanks,

James 🚀

**Comment by stuartfarr** [comment]
> Hey @stuartfarr - I'm currently updating the progression of the Timebase CE project contribution and was wondering if you have an update on inviting current Timebase customers to join the project contribution?
> 
> It would be great if you could supply an update in the issue comments below.
> 
> Kind regards,
> 
> James.

There are a couple of new (TimeBase CE prospects) that I hoped we would be able to, but it looks like they are going to fall into 2021 now.

**Comment by mindthegab** [comment]
Thanks @stuartfarr and the team of contributors for putting this forward. I think we should proceed with the contribution validation and onboarding, and then use the socialization phase to garner more contributors. 

@stuartfarr please let us know we can help once the project is contributed. Definitely existing prospects would be a great place to start to build a community.

Thanks!

**Comment by mcleo-d** [comment]
Thanks @mindthegab - I have setup a meeting with the Timebase team for Monday 18th January at 2:30pm GMT to move forward with next steps 👍  

James.

**Comment by mcleo-d** [comment]
The following update was received from @avavilau in the Timebase team ...

> - We’ve created all the repositories for all dependencies.
> - We’ve ported our CI scripts from gitlab pipelines to github workflows
> - We’ve started publishing artifacts to maven. (docker/artifacthub/nuget in progress)
> - We still need a bit more time to finish the process.

James.

**Comment by stuartfarr** [comment]
We are pleased to announce that our friends at crypto trading technology firm [mainbloq](https://mainbloq.io/)  will be the first consumer of TimeBase Community Edition.

**Comment by mdvx** [comment]
Absolutely thrilled to be working with TimeBase, we have big plans for this breakthrough technology.  Can't wait to get started!

**Comment by mcleo-d** [comment]
Hi @mdvx - It's an absolute pleasure to meet you and look forward to working with you and the TimeBase team when the project hits the FINOS organisation 🚀 

It would be great to catch up and talk about FINOS CCLAs so we can hit the ground running. Are you okay if @stuartfarr introduces us via email?

James.

cc @mindthegab @toshaellison @maoo

**Comment by mdvx** [comment]
Hi James

 

Nice to meet you, looking forward to working together.  Let me also Introduce you to Clay Cowdery who will be taking an active role in this deployment.

 

All good with Stuart doing intros.

 

Marc

**Comment by mdvx** [comment]
Hi Guys

anybody got a URL for the docker image?

@stuartfarr @mcleo-d

**Comment by mcleo-d** [comment]
Hi @mdvx 

Apologies for the time taken to respond. Let me email @avavilau and @stuartfarr to see how close the TimeBase team is to making the contribution and we'll get right back to you.

James.

**Comment by mcleo-d** [comment]
Hi @KimmoLinna

Thank you for meeting yesterday and for showing your initial interest in TimeBase CE as an open source alternative to KDB. 

I'd like to introduce you to @stuartfarr and the TimeBase team who I'm sure will be in touch once the project is contributed to FINOS.

Have a great weekend and speak soon.

James.

**Comment by stuartfarr** [comment]
Hi @mdvx 

Contribution to FINOS should be available in next 2 weeks: we will announce accordingly.

Thanks, Stuart

**Comment by mcleo-d** [comment]
Following a quick review of the [TimeBase](https://github.com/epam/TimeBase) project prior to FINOS contribution, the issue below describes prerequisites needed within the open source project as outlined in the FINOS [Contribution Compliance Requirements](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements) document.

- https://github.com/epam/TimeBase/issues/1

**Comment by stuartfarr** [comment]
Hi @mcleo-d 

Duly noted: TimeBase contribution will be ready 18th May but understood that subject to vulnerability scanning etc. for which we can provide @maoo the required access to the current EPAM/TimeBase repo.

**Comment by mcleo-d** [comment]
Hi @stuartfarr,

Thanks so much for your update. This is very exciting news! 🚀 

Feel free to send me a link to the main Timebase repo when the project is ready for review. 

James.

**Comment by mcleo-d** [comment]
@stuartfarr has confirmed [TimeBase](https://github.com/epam/TimeBase/) can move to the next stage of FINOS contribution alongside the completion of https://github.com/epam/TimeBase/issues/1 by the TimeBase team.

**Comment by maoo** [comment]
Hi @mcleo-d and @alex-karpovich ! I've raised https://github.com/finos/TimeBase-CE/pull/174 as I noticed that `NOTICE` file was still not correct.

Any update on the TimeBase logo, so that we can complete the project onboarding and complete the contribution process?

Thanks!

**Comment by maoo** [comment]
Quick status update - The TimeBase code is now hosted to https://github.com/finos/TimeBase-CE - congratulations to the EPAM team!

To complete the contribution process, we'd also like to:
1. solve a logo visualization issue on https://landscape.finos.org/
2. release on Maven Central and Docker (although not mandated by FINOS standard contribution process)
3. Enable LFX EasyCLA

**Comment by maoo** [comment]
Logo is fixed, see https://landscape.finos.org/

**Comment by maoo** [comment]
Project is registered in our internal systems, releases are done (soon README will be updated with badges).

Marking contribution as done, congrats to the EPAM team for this great contribution!
