### ISSUE TITLE
SIG Onboarding - DevOps Mutualization

### ISSUE THREAD

**Issue by mcleo-d** [finos/community#77]
## Business Problem
DevOps Mutualization aims to solve common engineering problems by providing a continuous compliance and assurance approach to DevOps that mutually benefits banks, auditors and regulators whilst accelerating DevOps adoption in engineering and fintech IT departments.
 
## Proposed Solution
Formation of FINOS Special Interest Group.
 
## Current State
DevOps Mutualization was designated a FINOS Special Interest Group through board approval on Wednesday 21st November 2020 and by the FINOS community through issue #61
 
## Existing Materials
  - DevOps Mutualization repository is currently in FINOS Labs awaiting transfer to the primary FINOS GitHub organisation  
    - https://github.com/finos-labs/devops-mutualization
  - DevOps Mutualization issues exist in https://github.com/finos/community/issues/ but reference new issues in FINOS Labs 
    - _Old_ : https://github.com/finos/community/issues?q=label%3Adevops-mutualization
    - _New_ : https://github.com/finos-labs/devops-mutualization/issues

## SIG Leadership Team
| Name | Email Address | FINOS Member | GitHub Profile | Role |
|:----|:----|:----|:----|:----|
| Amol Shukla | amol.shukla@morganstanley.com | Morgan Stanley  | @ashukla13 | Lead |
| Anders Wallgren | awallgren@cloudbees.com | CloudBees | @awallgren | Co-Lead (Secretary) |
| Dov Katz | dov.katz@morganstanley.com | Morgan Stanley | @dovops | |

# SIG Contribution and Onboarding process (v. 1.0, last updated on October 27, 2020)
Below is the list of tasks that FINOS Team and the contribution author goes through in order to complete the FINOS SIG onboarding process. **Please do not edit these contents at contribution time!**

## Voting (SIG Lead and FINOS ED)
- [x] Contribution author triggers community voting to propose SIG to FINOS board
- [x] Assign issue to Executive Director (@mindthegab) to trigger vote
- [x] (optional) at the discretion of the Executive Director: bring SIG to the Board for additional socialization and approval
- [x] FINOS board accepts the SIG (and the onboarding process can move forward)

## Identify project meta (Lead: FINOS SIG POC, Support: FINOS Marketing)
- [x] Identify and Assign FINOS SIG POC - @mcleo-d 
- [x] Link to SIG approval resolution - https://github.com/finos/community/issues/74#issuecomment-714804883
- [x] SIG Name - **DevOps Mutualization**
    - [x] Assess current trademark status - Not required https://github.com/finos/community/issues/77#issuecomment-749593015
    - [x] Define new SIG name - _// Not applicable at this point in time_
    - [x] Design new SIG logo - https://github.com/finos/metadata/issues/722
    - [x] Trademark new SIG name and logo (if applicable) - Not required https://github.com/finos/community/issues/77#issuecomment-749593015
- [x] Category and sub-category (for FINOS Landscape) - https://github.com/finos/metadata/issues/722
- [x] **Existing content/assets** or new Github repository - https://github.com/finos-labs/devops-mutualization/
- [x] Team composition: lead maintainer and other maintainers - See **SIG Leadership Team** table above
- [x] Meetings? (existing/**yes**/no)
- [x] Meeting minutes, agenda, attendance tracking (existing/**yes**/no)
- [x] Documentation website (existing/yes/**no**)
- [x] Define SIG slug - **devops-mutualization**

## Project Communication Channel(s)
- [x] Ask maintainers which communications channels they'd like to use and if more than one are needed. These may include
    - [x] Creation of one or more project mailing lists (e.g. general@, or dev@ and users@) 
      - DevOps Mutualization requires an email distribution list that enables SIG maintainers to communicate with the community.
      - The suggested email addresses are devops-mutualization@finos.org and devops-mutualization+subscribe@finos.org.   
      - [x] devops-mutualization@finos.org distribution list created.
    - [x] Creation of one or more Slack or Symphony chats for the project - _// Not required at this point in time_
- [x] Create the identified communication channels during infra set up
   - GitHub Teams proposed as 'in-line' communication channel for private thread use.  
- [x] Link communication channels linked front and center in the project README.md.

## Repository transfer (Lead: FINOS Infra)
- [x] Check GitHub repository transfer requirements:
  - [x] [finos-admin](http://github.com/finos-admin) has `Admin` to all repositories to transfer
  - [x] [finos-admin](http://github.com/finos-admin) is allowed to transfer repositories out of the org
  - [x] if the repository is owned by a user (and not an org), the user must be able to transfer the repository to [finos-admin](http://github.com/finos-admin)
- [x] Transfer all assets as GitHub repositories under github.com/finos
- [x] Invite GitHub usernames to GitHub FINOS Org
- [x] Create `<sig-name>-maintainers` GitHub team and invite users - https://github.com/finos/community/issues/77#issuecomment-739967473

## Infra setup (Lead: FINOS Infra)
- [x] Update SIG badge - https://github.com/finos/devops-mutualization/pull/10
- [x] Update SIG README - https://github.com/finos/devops-mutualization/pull/11
- [x] Enable meeting attendance tracking (optional) - https://github.com/finos/open-developer-platform/issues/200

## Metadata update (Lead: FINOS Infra)
- [x] Add SIG to metadata - https://github.com/finos/metadata/pull/764
- [x] Add identities, orgs and affiliations to metadata - https://github.com/finos/metadata/pull/764
- [x] Add logo to FINOS landscape - _Dependency_ - https://github.com/finos/metadata/issues/722
- [x] Add SIG Leads emails to finos-project-maintainers@finos.org list
- [x] Add SIG Leads GitHub usernames to the project-maintainers Team - https://github.com/finos/metadata/issues/788

## Announcement (Lead: FINOS POC)
- [x] Work with FINOS marketing to send out announcement to announce@finos.org , checkout announcement template at https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/83034172/Contribute
- Notify FINOS POC and FINOS marketing manager once the announcement has been sent out (FINOS infra) - https://github.com/finos/finos-marketing/issues/101
- Coordinate social media promotion with FINOS marketing - https://github.com/finos/finos-marketing/issues/101 
    - Post on FINOS social media - https://github.com/finos/finos-marketing/issues/101
    - Post on LF social media - https://github.com/finos/finos-marketing/issues/101

## Contributors Metadata (Lead: FINOS SIG POC, Support: FINOS infra)
- [x] For each SIG material contributor identified in the previous step, collect: the following info:
  - Fullname
  - GitHub username
  - Corporate email address
- [x] Identify other existing contributors (assuming there's a contribution history (eg Git history)

**Comment by mcleo-d** [comment]
[DevOps Mutualization Maintainers Team](https://github.com/orgs/finos/teams/devops-mutualization-maintainers) created on GitHub with @ashukla13 and @awallgren invited to join. 

- [x] @ashukla13 accepted DevOps Mutualization Maintainers Team invite.
- [ ] @awallgren accepted DevOps Mutualization Maintainers Team invite.

**Comment by mcleo-d** [comment]
@toshaellison and @mindthegab 

Can you confirm if the following tasks are required for DevOps Mutualization ...

- Assess current trademark status - // To be assessed
- Trademark new SIG name and logo (if applicable)

Many thanks,

James.

**Comment by toshaellison** [comment]
@mcleo-d neither of those are required for the DevOps Mutualization SIG. Thanks.

**Comment by mcleo-d** [comment]
The DevOps Mutualization contribution is now done 😄
