### ISSUE TITLE
Proposal for the creation of a 'InnerSource' Special Interest Group

### ISSUE THREAD

**Issue by claredillon** [finos/community#84]
## Business Problem
InnerSource can help break down silos, encourage internal collaboration and innovation, accelerate new engineer on-boarding, and identify opportunities to contribute software back to the open source world.

## Proposed Solution
Formation of an InnerSource Special Interest Group. 

The InnerSource SIG will be a community of people interested in implementing InnerSource within their organization. 

This SIG will be of particular importance to Financial Organisations who wish to accelerate their InnerSource practices, share best practices, patterns and anti-patterns and potentially related code (e.g. for InnerSource tooling) in a secure environment, with an aim of submitting proven methods and code upstream to InnerSourceCommons.org. Discussions will have an emphasis on challenges and concerns that are particular to FS organizations (e.g. relating to compliance or regulatory constraints).

The target audience will be individuals responsible for InnerSource implementation within Financial Services organizations, those in Open Source Program Offices interested in open source culture, behaviour and skills, or tech leaders wishing to increase collaboration and remove deal with excessive ownership issues that can stall innovation.  

## Current State
*Summarize the history and current state of the special interest group*

## Existing Materials
InnerSource Commons GitHub repository to be potentially forked into FINOS for upstream contributions of Financial Services related materials to InnerSource Commons : 
- https://github.com/InnerSourceCommons

## SIG Leadership Team
The proposed chair of the InnerSource SIG will be Danese Cooper @danese (NearForm and President of the InnerSource Commons) and initial sponsors will include Royal Bank of Canada and representatives from additional financial institutions. 

# SIG Contribution and Onboarding process (v. 1.0, last updated on October 27, 2020)
Below is the list of tasks that FINOS Team and the contribution author goes through in order to complete the FINOS SIG onboarding process. **Please do not edit these contents at contribution time!**

## Voting (SIG Lead and FINOS ED)
- [x] Contribution author triggers community voting to propose SIG to FINOS board - Done through issue #87
- [x] Assign issue to Executive Director (@mindthegab) to trigger vote - Vote issue assigned to @mindthegab
- [x]  Executive Director brings SIG to the Board for additional socialization and approval
- [x] FINOS board accepts the SIG (and the onboarding process can move forward)

## Identify project meta (Lead: FINOS SIG POC, Support: FINOS Marketing)
- [x] Identify and Assign FINOS SIG POC - FINOS SIG POC is @mcleo-d (@agitana also invited)
- [x] Link to SIG approval resolution - https://github.com/finos/community/issues/84#issuecomment-765073635 
- [x] SIG Name - **InnerSource**
    - [x] Assess current trademark status - @danese to have wider conversations with FINOS (@mindthegab and @toshaellison)
    - [x] Define new SIG name (if applicable) - _not applicable_
    - [x] Design new SIG logo (if applicable) - https://github.com/finos/branding/pull/17
    - [X] Trademark new SIG name and logo (if applicable) - No need
- [x] Category and sub-category (for FINOS Landscape) - Categorisation is **OSS Readiness** on the [FINOS Landscape](https://landscape.finos.org/)
- [x] Existing content/assets or new Github repository - New InnerSource GitHub repository - https://github.com/finos/metadata/issues/837
  - Contributed materials to the InnerSource SIG repo will be pushed to https://github.com/InnerSourceCommons/InnerSourcePatterns so the InnerSource SIG owns FS contributions which are consumed by the ISC upstream to live with all other ISC materials. The mechanism of material delivery to ISC to be done by the InnerSource SIG and discussed with FINOS.
- [x] Team composition: lead maintainer and other maintainers
- [x] Meetings? (existing/yes/no) - **yes**
- [x] Meeting minutes, agenda, attendance tracking (existing/yes/no) - **yes** - https://github.com/finos/metadata/issues/837
- [x] Documentation website (existing/yes/no) - **no**
- [x] Define SIG slug : Dependant on `Define new SIG name` - _not applicable_

## Project Communication Channel(s)
- [x] Ask maintainers which communications channels they'd like to use and if more than one are needed. These may include
    - [x] Creation of one or more project mailing lists (e.g. general@ & leadership@)
    - [x] Creation of one or more Slack or Symphony chats for the project - _not required_
- [x] Create the identified communication channels during infra set up
- [x] Link communication channels linked front and center in the project README.md.

## Infra setup (Lead: FINOS Infra)
- [x] Update SIG badge - _not required_
- [x] Update SIG README - https://github.com/finos/InnerSource/issues/4
- [x] Enable meeting attendance tracking (optional)

## Metadata update (Lead: FINOS Infra)
- [x] Add SIG to metadata - https://github.com/finos/metadata/pull/867
- [x] Add identities, orgs and affiliations to metadata
- [x] Add logo to FINOS landscape - https://github.com/finos/finos-landscape/pull/89
- [x] Add SIG Leads emails to finos-project-maintainers@finos.org list
- [x] Add SIG Leads GitHub usernames to the project-maintainers Team

## Announcement (Lead: FINOS POC)
- [x] Work with FINOS marketing to send out announcement to announce@finos.org , checkout announcement template at https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/83034172/Contribute - https://github.com/finos/InnerSource/issues/5, https://github.com/finos/finos-marketing/issues/164#issuecomment-792833017
- [x] Notify FINOS POC and FINOS marketing manager once the announcement has been sent out (FINOS infra) - https://github.com/finos/InnerSource/issues/5, https://github.com/finos/finos-marketing/issues/164#issuecomment-792833017

## Press Release (OPTIONAL) (Lead: FINOS POC)
- [ ] Identify quotes for press release
- [ ] Draft press release
- [ ] Send embargoed press release to reporters
- [ ] InnerSource SIG Promotion on FINOS Marketing - https://github.com/finos/finos-marketing/issues/170

## Onboarding and training
- [x] FINOS SIG Governance
- [x] FINOS Project Lifecycle _not required_
- [x] ODP Training _not required_

**Comment by mcleo-d** [comment]
@claredillon and @danese,
 
This is to note as part of the ISC SIG proposal the InnerSource Commons at Open Source Readiness event scheduled for Wednesday 9th December 2020 at 3pm GMT / 10am ET

- https://www.finos.org/hosted-events/2020-12-09-innersource-commons-at-open-source-readiness

Organisers, speakers and panelists at this event include ... 

- Danese Cooper - InnerSource Commons
- Clare Dillon - InnerSource Commons
- Arthur Maltson - Capital One
- Daniela Zheleva - Deutsche Bank 
- Pooi Cheong - Lloyds Banking Group

**Comment by mcobby** [comment]
We strongly believe that InnerSource has a strong strategic alignment with Financial Services and have built an Inner Source team at National Australia Bank to promote it.

**Comment by mcleo-d** [comment]
Thanks for your comment @mcobby. 

It's great to have your comments and support of the InnerSource Special Interest Group.

At FINOS we've just launched our first APAC meetup - https://www.finos.org/blog/finos-apac-meetup-november-2020  

It'll be great to see you at the January event that's currently being planned ... 😸 

James.

**Comment by johnmark** [comment]
Great to see this +1 - please let us know how Capital One can contribute.

**Comment by lspiro-Tick42** [comment]
At Glue42, we offer our larger clients, a Shared Source model as an alternative to Escrow. Glue42 source code is submitted to the client's repo and scanned and built on their site, but ownership and Copyright to Glue42 remains with us and a valid licence is required to use Glue42 and anything derived from it.

If we are considering Inner Source best practice, we think it would be useful to have a way to label such 3rd party repositories to ensure that in-house developers know how to treat the code. 

Does anyone else think this is a use case worth discussing ?

**Comment by junjikatto** [comment]
Hello!

**Comment by rheironimus** [comment]
👍 Great idea.  Freddie Mac would like to participate and contribute.

**Comment by lhawthorn** [comment]
+1 - excited and interested to learn more about how InnerSource adds value within financial organizations

**Comment by lspiro-Tick42** [comment]
+1 - I think this is relevant to FINOS

**Comment by mcleo-d** [comment]
This +1 was obtained from Matthew Dietz at BNY Mellon via email.

Thank you.

James.

**Comment by kanchai123** [comment]
+1 very exciting initiative! 👍 Looking forward for this great initiative.

**Comment by jbjonesjr** [comment]
👍

**Comment by jomarsilvazup** [comment]
+1

**Comment by kanchai123** [comment]
+1

**Comment by mindthegab** [comment]
This Special Interest Group was approved by the Board on January 20th 2021.  

Thank @claredillon and the rest of the team for putting this forward. 

Congratulations not only for the Board approval but for the outstanding level of support expressed by the Community during the socialization process.

Glad we can support this initiative and looking forward to doing amazing things together  🚀

**Comment by godds** [comment]
+1

**Comment by chriskurzeja** [comment]
+1

**Comment by mcleo-d** [comment]
> Assess current trademark status - @Danese to have wider conversations with FINOS (@mindthegab and @toshaellison)

@danese and @claredillon

I have spoken to @mindthegab regarding the SIG onboarding question highlighted above and the FINOS team has no intention or desire to have the InnerSource trademark contributed to the foundation. We are happy for you to give FINOS license to use the term InnerSource as and when appropriate.

This means we'll move forward with the creation of the InnerSource repository, plus other SIG dependencies, and will wait for you to engage with the FINOS team as and when you are ready to grant license.

James.

**Comment by mindthegab** [comment]
Providing some color regarding the trademark conversations above, I will follow up with @danese and @mcleo-d offline as this is not the best place for legal conversations - nevertheless I don't see any blocker in proceeding with the contribution and the production of a logo completely independent from any Innersource Commons existing artwork.

**Comment by ColinEberhardt** [comment]
Any update on when this SIG will start holding meetings and how to attend? Thanks

**Comment by claredillon** [comment]
> Any update on when this SIG will start holding meetings and how to attend? Thanks

Hi Colin - excellent timing. A couple of updates from the last few days:
1. We'll be having our next InnerSource / OSR meeting on March 3rd - details for registration etc will be out shortly. 
2. We are working through the steps to get the official InnerSource SIG site/mailing lists etc set up - here are the details from the PR: Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by maoo** [comment]
All done, contribution completed, congratulations everyone!
